name: build and push Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: { java-version: 8 }
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
    - run: mvn --batch-mode --show-version --no-transfer-progress -Pcoverage install
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: build and push the image
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rdohna/wildfly-ping .
