name: build and push Docker image

on:
  push:
  pull_request:
  schedule: [ cron: '12 1 * * 5' ] # weekly: At 01:12 on Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
    - name: Maven build
      run: mvn --batch-mode --show-version --no-transfer-progress install
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: build and push the image
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rdohna/wildfly-ping .
