name: build and push Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u rdohna --password-stdin
    - name: install buildx
      run: docker buildx create --use
    - name: build and push the image
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rdohna/wildfly-ping .
